### ISSUE TITLE
[FR] Emoji Support

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1478]
## Brief
Support opening the Emoji panel by selection menu (i.e. slash menu) and inserting Emoji in AppFlowy.

## Details
**Tasks**
> Please link each commit to the relevant task below.
- [ ] open the emoji panel by the selection menu.
  - [ ] open the emoji panel by searching for the keyword `emoji`.
  - [ ] open the emoji panel by tapping the emoji entry.
- [ ] select an emoji by clicking on the emoji panel.
  - [ ] the emoji panel can slide up and down, and can be extended for more emojis.
- [ ] select an emoji by keywords.
  - [ ] only show the emojis that match the keyword.
  - [ ] show no result widget if no matching emojis.
- [ ] press the `ESC` key to exit the emoji panel.

https://user-images.githubusercontent.com/11863087/203695166-cba1328b-d2e6-4bde-81d1-ce1643338cac.mov

**Test cases**
- [ ] include the relevant tests that match the tasks mentioned above.
- [ ] check the performance on the desktop platform (Windows, Linux, macOS) and web platform.

### Impact

The end-users who want to insert emojis in their document can benefit from this feature.

### Additional Context

**Reference**

* [Customize the selection menu in appflowy_editor.](https://pub.dev/documentation/appflowy_editor/latest/appflowy_editor/AppFlowyEditor/selectionMenuItems.html)
* Selection menu item style
  * the size of the icon widget should be 18.0.
  * Use the Flutter built-in icon `Icons.emoji_emotions_outlined` as the thumbnail.
  * Use l10n for the name of the item.
* [Testing the appflowy_editor](https://github.com/AppFlowy-IO/AppFlowy/blob/main/frontend/app_flowy/packages/appflowy_editor/documentation/testing.md) If you modify the relevant code.

**Comment by rizwan3395** [comment]
I have done the Task. Let me know the next step.

**Comment by rizwan3395** [comment]
Hi @LucasXu0 Can you guide me in which branch I should create a pull request?

**Comment by rizwan3395** [comment]
I'm only seeing the main branch while creating a pull request, Don't know what mistake I did.

**Comment by LucasXu0** [comment]
@rizwan3395 There is a guideline about how to make a pull request. [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

Basically, you need to fork the appflowy repository, submit your code to your own repository and then make a pull request.
