### ISSUE TITLE
[FR] Customize Font Size In AppFlowy

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#1479]
## Brief
Support customizing the font size in AppFlowy.

## Details
> Please link each commit to the relevant task below.

**Tasks**
- [x] support switch font size with small, medium, and large.
- [x] add a `more` button to the title bar beside the `share` button.
- [x] add an entry for font size switching after clicking the `more` button.

**Test cases**
- [ ] include the relevant tests that match the tasks mentioned above.

### Impact

The end-users who want to switch the font size.

**Comment by annieappflowy** [comment]
Should test across mainstream operating systems
