### ISSUE TITLE
[FR] Importers

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/AppFlowy#2706]
### Description

Allow users to import their data from 3rd sources eg: Notion ,Joplin

Example - 
In notion we can export all our workplace contents .
![Screenshot from 2023-06-05 10-12-28](https://github.com/AppFlowy-IO/AppFlowy/assets/71614009/641a76a9-d9e1-4e3a-8410-ae52e11f81a3)
 It provides us with a zip folder that contains all the pages, subpages, and databases (as CSV files).
In AppFlowy, there should be an option to upload that folder, which will then populate all the corresponding pages and subpages in the correct manner.

#### Tasks
- [ ] Convert Notion document page to AppFlowy document page
  - [ ]  Rust --> Write now there is a option to import a single file to import ,we need to extend this functionality to support upload of a folder because when we export a page from notion it will give us a folder which will contain a markdown file and a another folder containing the assets of that page .
  - [ ] Flutter --> In a page there should be a option to import contents to that page form the folder provided by notion
- [ ]   Convert Notion calendar to AppFlowy calendar 
  - [ ] Rust --> Support populating the Calendar page from the imported folder which contains a csv file and a folder containing markdown file of notes for each date.
  - [ ] Flutter -->  Add a option on calendar page to import data
- [ ]   Convert Notion  board to AppFlowy Board
  - [ ] Rust --> Populating the board with the data from the CSV file which contains information regarding the column under which each card should be placed on the board . Then there is a folder containing contents of each card So we need to populate the cards with their respective contents.
  - [ ] Flutter --> Add a option on Import panel to import board from notion
- [ ]  Option to upload the the contents of complete workspace form notion to AppFlowy
  - [ ] Rust --> When we export our workspace we get a folder which contains many sub folders having information regarding each page .So we need to populate all the pages and subpages in correct manner including all databases calendars and boards
  - [ ] Flutter --> In setting there can be an option to import data from notion
### Impact

Users who want to migrate to AppFlowy and import all there data to AppFlowy

**Comment by Mukund-Tandon** [comment]
@LucasXu0  please can you review this .

**Comment by LucasXu0** [comment]
Hey, @Mukund-Tandon. Nice. I suggest you add more details about it, for example.

* convert notion document page to appflowy document page.
    * Rust side
        * task 1, support importing single file.
        * task 2, suport importing multiple files. 
        * task 3, support importing a zip file.
        * ...
    * Flutter side
        * implement the UI ...
* convert notion database page to appflowy database page.
    ...

**Comment by Mukund-Tandon** [comment]
Ok so I will edit the above description to include list of task and sub task which need to be done to implement this feature

**Comment by Mukund-Tandon** [comment]
@LucasXu0   I have updated the issue description with the tasks that need to be performed. Could you please review them

**Comment by LucasXu0** [comment]
Great. I converted a bulleted list into a to-do list. You can change the "to-do" to a "new issue" when starting a new feature.

<img width="1541" alt="Screenshot 2023-06-12 at 10 17 11" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/68aee5fc-402e-49d1-9479-be03e52c1517">

FYI, there's already an import option in `+` button. You should add the import from XXX inside.

<img width="168" alt="Screenshot 2023-06-12 at 10 18 31" src="https://github.com/AppFlowy-IO/AppFlowy/assets/11863087/e9ea47c7-610b-45e2-ad1d-66da5303f243">

**Comment by wwwdyne** [comment]
@qinluhe @annieappflowy 

I'm looking at the following subtask: "Convert Notion calendar to AppFlowy calendar".
Notion Calendar has recurring tasks support (out-of-the-box). Appflowy unfortunately still has not.
So I think before implementing this task (Convert Notion calendar to AppFlowy calendar), both these tasks should be implemented:

https://github.com/AppFlowy-IO/AppFlowy/issues/3437
https://github.com/AppFlowy-IO/AppFlowy/issues/2380

Could anyone please assign a qualified software engineer for it?

**Comment by annieappflowy** [comment]
Notion importer is here: https://appflowy.io/compare/notion-vs-appflowy
