### ISSUE TITLE
[Doc] AppFlowy Personal Cloud Private Beta

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#3125]
## Define your goals
- Thoroughly test the personal cloud functionality to guarantee smooth local data backup and seamless cross-device access, addressing any potential data loss issues.
- Extend user outreach to gather comprehensive product feedback from a broader user base.
- Enhance AppFlowy's visibility to increase awareness among a wider audience.

## Define the target outcomes
- Validate the stability of the personal cloud for a seamless public beta experience.
- Aim to receive valuable feedback from at least 20% of 5,000 users during this period (1st round).
- Targeting a public beta launch in two months (tentative).

## Identify your participants
- Existing AppFlowy users who are eager to use the Cloud functionality.
- New users who are willing to adopt AppFlowy with an understanding of potential product instability during the beta phase.
- Contributors, influencers, and writers who are interested in testing AppFlowy and providing their valuable feedback.

## Distribute testing information starting on August 15th
- Send a signup form to target users (Discord --> Twitter --> Email List --> Website --> Other platforms) 
- Screen qualified beta testers
- Email a download link / access code with instructions

This may include product access materials like installation packages, download links, user guides, issue logging instructions, and anything else needed to facilitate the test.

## To-Dos
- [x] signup form
- [x] documentation
- [x] forum set up
- [x] beta tester award program
- [x] Windows package ready
- [x] Linux package ready
- [x] invite email
- [ ] blog post
- [x] email subscribers
- [ ] a new video marketing asset
- [ ] risks and mitigations

### Impact

Users who want to back up data to cloud and sync across devices

**Comment by IMPranshu** [comment]
Hey @annieappflowy. I would like to test this and give my feedback. How to get started?

**Comment by annieappflowy** [comment]
You can sign up via filling out a form which will be shared next week.

**Comment by anhhtbk** [comment]
Can you provide an update on the progress?

**Comment by annieappflowy** [comment]
It's on the private beta mode @anhhtbk

**Comment by miztizm** [comment]
Waiting with impatience, it's the only thing that keeps me from moving to Appflowy.

**Comment by adriy-be** [comment]
Hello, any news ? How to join the beta ?
I'm currently using Joplin with a self-hosted Joplin server, I'm really interesting to try and migrate to AppFlowy.

**Comment by annieappflowy** [comment]
Hi @miztizm @adriy-be , please [sign up](https://survey.appflowy.io/private-beta) for the Cloud beta
@adriy-be , have you tried self-hosting [AppFlowy with Supabase](https://blog.appflowy.io/self-hosting-appflowy-free-using-supabase/)?

**Comment by adriy-be** [comment]
> Hi @miztizm @adriy-be , please [sign up](https://survey.appflowy.io/private-beta) for the Cloud beta @adriy-be , have you tried self-hosting [AppFlowy with Supabase](https://blog.appflowy.io/self-hosting-appflowy-free-using-supabase/)?

Interesting ! I check that on my free time.
It's seem more complex than just deploy a container like [Joplin server](https://github.com/flosoft/docker-joplin-server) but supabase seem very interesting.
Thanks

**Comment by eitzenbe** [comment]
Hi Annie, I have cloud version 0.3.8 docker hosted on one of my servers, but it seems this is not providing features like sharing pages amongst users accessing the server from different machines. I#d be happy to do beta tesing with a few colleagues if such a version is lurking around ;)

**Comment by TheRealGramdalf** [comment]
I'm also interested in self-hosting appflowy, but in my perusal of the supabase guide it wasn't quite clear how everything fits together. Is there some guide I'm missing that can get me kickstarted with docker-compose? Or is deploying supabase the only thing to do, and appflowy takes the rest from there (once you've run the database setup etc.)?

**Comment by annieappflowy** [comment]
@TheRealGramdalf , if you need help with self-hosting, please join our [Discord](https://discord.gg/9Q2xaN37tV) server so we can offer quick support.

**Comment by xiaoxiaoimg** [comment]
At present, it is a bit troublesome to use docker-compose to deploy, so why not host it on docker? docker run xxx?

**Comment by Snuupy** [comment]
looks like reminders on cloud beta isn't working (it is working on local)

**Comment by speed2exe** [comment]
@xiaoxiaoimg Appflowy Cloud comprises of a few services running. You could run each of them individually. docker compose makes the process easier.

**Comment by speed2exe** [comment]
@Snuupy What do you mean reminders on cloud beta isn't working? As far as I know, reminder are a local feature.

**Comment by Snuupy** [comment]
> @Snuupy What do you mean reminders on cloud beta isn't working? As far as I know, reminder are a local feature.

![image](https://github.com/AppFlowy-IO/AppFlowy/assets/964538/31f0159d-f8c5-4eb1-84a1-2446cb047afc)
![image](https://github.com/AppFlowy-IO/AppFlowy/assets/964538/1f8d4970-bc55-4297-bce0-7786cb80dd7b)

Even if I set a reminder in a shared workspace, it won't show up in Upcoming Notifications. I expected it to work as it did locally, that I would receive a notification if something was due.

**Comment by therynamo** [comment]
Hey! Just wanted to say thank you so much for building this all in open source and offering a self hosted option. I'm very excited and hoping that AppFlowy can be our home Knowledge Base. 

One thing with the self hosted cloud is this known issue: https://github.com/AppFlowy-IO/AppFlowy/issues/4568 

This is a really important feature for us in order to fully realize your platform. 

I'm positive this is not a trivial issue, so I understand if it's still ongoing development. I'm hoping this is shored up sooner than later, but I know you all have your hands full. Any chance there is an update? (No pressure)

You've got a nice cross platform app here with an intuitive and easy to use UI. I'm very excited for what comes next for this project and team. Thanks again!

**Comment by annieappflowy** [comment]
@Snuupy , reminders syncing across devices should be fixed

**Comment by Fau57** [comment]
I'd love to be involved in any way I could for this
