### ISSUE TITLE
[Workflow] Create a public project tracking system that foster better collaboration

### ISSUE THREAD

**Issue by annieappflowy** [AppFlowy-IO/AppFlowy#378]
- [x] set up a project tracker
- [ ] document how to use it
- [ ] announce it on Discord 
- [ ] Collect feedback and iterate

**Comment by MidouWebDev** [comment]
I can help. I will just need more informations.

@annieappflowy

**Comment by annieappflowy** [comment]
> I can help. I will just need more informations.
> 
> @annieappflowy

Hi @MidouWebDev , thanks for offering the help. This issue has been claimed by @Hari-07 . You are welcome to provide feedback once it's drafted.

**Comment by aarhusgregersen** [comment]
Has there been any progress on this? I see a lot of documentation existing, so thinking this may perhaps already be covered?

**Comment by annieappflowy** [comment]
This task is done. Please check out: https://github.com/orgs/AppFlowy-IO/projects/5
Closing this issue now.
