### ISSUE TITLE
[FR] Master issue for Code Block improvements 

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/AppFlowy#5247]
### Description

Improvements:
- [ ] Enable hide line numbers
- [ ] Show the language that is guessed by the "Auto" option
- [ ] Allow changing the indentation level
- [ ] Bracket completion
- [ ] Collapse code block
- [ ] Auto indentation improvement after opening brakcet

### Impact

More control over the behavior of the code block depending on the usage and language.

### Additional Context

Code block is over at https://github.com/AppFlowy-IO/AppFlowy-plugins

Much of the implementations can be done in the main repository, but there is a need for some enablers in the plugins repository.

**Comment by smartyhero** [comment]
Can it support automatic line wrapping switching?

**Comment by Xazin** [comment]
> Can it support automatic line wrapping switching?

Yes, I need to find a suitable implementation for line number replacement when wrapping lines though.

**Comment by smartyhero** [comment]
I'm not sure if I described it clearly, I need a function like this

https://github.com/AppFlowy-IO/AppFlowy/assets/76774978/0e2b1578-36f2-4d2a-8236-31110d2f1911
