### ISSUE TITLE
[Improvement] support meta + shift + arrow key

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/AppFlowy#953]
**Meta + Shift + Arrow**
- [ ] Meta + Shift + Up = Select all elements in front of the current cursor.
- [ ] Meta + Shift + Down = Select all elements behind the current cursor.
- [ ] Meta + Shift + Left = Selects all content in front of the current cursor in the current element.
- [ ] Meta + Shift + Up = Selects all content behind the current cursor in the current element.

**Meta + Arrow**
- [ ] Meta + Up = Moves the cursor to the topmost of the document.
- [ ] Meta + Down = Moves the cursor to the bottommost of the document.
- [ ] Meta + Left = Moves the cursor to the leftmost of the current element.
- [ ] Meta + Right = Moves the cursor to the rightmost of the current element.

**Example**
https://user-images.githubusercontent.com/11863087/187618301-cf925bd9-f40f-4a51-be70-c4d63117abf0.mov

**Comment by skewballfox** [comment]
Definitely make this reassignable, otherwise this will conflict with common keybindings for both [sway](https://swaywm.org/) and [i3](https://i3wm.org/)

**Comment by LucasXu0** [comment]
Got it. I will open a new issue to support customizing the hotkeys.
